# Generated by Django 6.0.5 on 2026-06-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
