# Generated by Django 6.0.5 on 2026-06-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia", "0002_curso_activo"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="valor_matricula",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
